version: '2'

volumes:
  elasticsearch:

services:

  elasticsearch:
    image: elasticsearch:latest
    restart: unless-stopped
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:latest
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

