version: '2'

volumes:
  elasticsearch:

services:

  elasticsearch:
    image: elasticsearch:latest
    restart: unless-stopped
    ports:
      - 23489:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  
  kibana:
    image: kibana:latest
    restart: unless-stopped
    ports:
      - 23488:5601
    depends_on:
      - elasticsearch

